/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.RegistroCliente;
import controlador.Validador;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Cuenta;

/**
 *
 * @author Katzewy
 */
public class Menu extends javax.swing.JFrame {

    RegistroCliente rc = new RegistroCliente();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipoDeCuenta = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblIcono = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        lblIngresar = new javax.swing.JLabel();
        lblRut = new javax.swing.JLabel();
        lblTipoDeCuenta = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        txtRut = new javax.swing.JTextField();
        optAhorro = new javax.swing.JRadioButton();
        optCorriente = new javax.swing.JRadioButton();
        lblMensajeError = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mAcciones = new javax.swing.JMenu();
        miDepositar = new javax.swing.JMenuItem();
        miRetirar = new javax.swing.JMenuItem();
        miSalir = new javax.swing.JMenuItem();
        mConsultas = new javax.swing.JMenu();
        miMostrarInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco");

        jPanel1.setBackground(new java.awt.Color(251, 224, 251));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/bank-icon.png"))); // NOI18N
        lblIcono.setDisabledIcon(null);
        lblIcono.setRequestFocusEnabled(false);

        lblBienvenida.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(50, 3, 51));
        lblBienvenida.setText("Bienvenido al Banco Virtual");

        lblIngresar.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lblIngresar.setForeground(new java.awt.Color(102, 102, 102));
        lblIngresar.setText("Ingresar");

        lblRut.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        lblRut.setForeground(new java.awt.Color(51, 51, 51));
        lblRut.setText("Ingrese el rut");

        lblTipoDeCuenta.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        lblTipoDeCuenta.setForeground(new java.awt.Color(51, 51, 51));
        lblTipoDeCuenta.setText("Tipo de cuenta");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        txtRut.setBackground(new java.awt.Color(255, 255, 255));

        optAhorro.setBackground(new java.awt.Color(255, 255, 255));
        bgTipoDeCuenta.add(optAhorro);
        optAhorro.setForeground(new java.awt.Color(0, 0, 0));
        optAhorro.setSelected(true);
        optAhorro.setText("Ahorro");
        optAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAhorroActionPerformed(evt);
            }
        });

        optCorriente.setBackground(new java.awt.Color(255, 255, 255));
        bgTipoDeCuenta.add(optCorriente);
        optCorriente.setForeground(new java.awt.Color(0, 0, 0));
        optCorriente.setText("Corriente");

        lblMensajeError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(lblBienvenida)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(lblIngresar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRut))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTipoDeCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(optAhorro)
                                .addGap(18, 18, 18)
                                .addComponent(optCorriente))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnAceptar)))
                .addGap(26, 26, 26)
                .addComponent(lblMensajeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIcono)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblBienvenida)))
                .addGap(9, 9, 9)
                .addComponent(lblIngresar)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRut)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoDeCuenta)
                    .addComponent(optAhorro)
                    .addComponent(optCorriente))
                .addGap(18, 18, 18)
                .addComponent(btnAceptar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mAcciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mAcciones.setText("Acciones");

        miDepositar.setText("Depositar");
        miDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDepositarActionPerformed(evt);
            }
        });
        mAcciones.add(miDepositar);

        miRetirar.setText("Retirar");
        miRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRetirarActionPerformed(evt);
            }
        });
        mAcciones.add(miRetirar);

        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        mAcciones.add(miSalir);

        jMenuBar1.add(mAcciones);

        mConsultas.setText("Consultar");
        mConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsultasActionPerformed(evt);
            }
        });

        miMostrarInfo.setText("Mostrar Informacion ");
        miMostrarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMostrarInfoActionPerformed(evt);
            }
        });
        mConsultas.add(miMostrarInfo);

        jMenuBar1.add(mConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDepositarActionPerformed
        Depositar deposita = new Depositar();
        deposita.setVisible(true);
    }//GEN-LAST:event_miDepositarActionPerformed

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miSalirActionPerformed

    private void miRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRetirarActionPerformed
        Retirar retirar = new Retirar();
        retirar.setVisible(true);
    }//GEN-LAST:event_miRetirarActionPerformed

    private void optAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAhorroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optAhorroActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String rut;
        char tipoCuenta;
        boolean ahorro, corriente;
        
        //Validacion de campos
        rut = txtRut.getText();
        if(Validador.validarTexto(rut) == false) {
            lblMensajeError.setText("*Ingrese rut");
            return;
        }
        else{
            lblMensajeError.setText("");
        }
        ahorro = optAhorro.isSelected();
        corriente = optCorriente.isSelected();
        if(corriente){
            tipoCuenta = 'C';
        }
        else{
            tipoCuenta = 'A';
        }
        
        //Crear cliente
        Cuenta cu = new Cuenta(tipoCuenta, 0);
        Cliente cl = new Cliente(rut, cu);
        if (rc.agregar(cl)) {
            JOptionPane.showMessageDialog(null, "Cliente" + cl.getRut() + " ingresado", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Cliente " + cl.getRut() + " no ingresado", "Validación", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void mConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mConsultasActionPerformed

    private void miMostrarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMostrarInfoActionPerformed
        Mostrar mostrar = new Mostrar();
        mostrar.setVisible(true);
    }//GEN-LAST:event_miMostrarInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch(ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch(InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch(IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch(javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipoDeCuenta;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblIngresar;
    private javax.swing.JLabel lblMensajeError;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblTipoDeCuenta;
    private javax.swing.JMenu mAcciones;
    private javax.swing.JMenu mConsultas;
    private javax.swing.JMenuItem miDepositar;
    private javax.swing.JMenuItem miMostrarInfo;
    private javax.swing.JMenuItem miRetirar;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JRadioButton optAhorro;
    private javax.swing.JRadioButton optCorriente;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
