package vista;

import controlador.RegistroCliente;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;

public class Mostrar extends javax.swing.JFrame {

    /**
     * Creates new form Mostrar
     */
    public Mostrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblMostrarInfo = new javax.swing.JLabel();
        lblRut = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        chkAhorro = new javax.swing.JCheckBox();
        chkCorriente = new javax.swing.JCheckBox();
        lblTipoCuenta = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mostrar");

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Rut Usuario", "Tipo de Cuenta", "Saldo"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        lblMostrarInfo.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        lblMostrarInfo.setForeground(new java.awt.Color(51, 51, 51));
        lblMostrarInfo.setText("Mostrar información de las cuentas");

        lblRut.setForeground(new java.awt.Color(51, 51, 51));
        lblRut.setText("Ingrese rut");

        txtRut.setBackground(new java.awt.Color(255, 255, 255));
        txtRut.setForeground(new java.awt.Color(0, 0, 0));

        chkAhorro.setBackground(new java.awt.Color(255, 255, 255));
        chkAhorro.setForeground(new java.awt.Color(0, 0, 0));
        chkAhorro.setText("Ahorro");

        chkCorriente.setBackground(new java.awt.Color(255, 255, 255));
        chkCorriente.setForeground(new java.awt.Color(0, 0, 0));
        chkCorriente.setText("Corriente");

        lblTipoCuenta.setForeground(new java.awt.Color(51, 51, 51));
        lblTipoCuenta.setText("Tipo de cuenta");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(lblMostrarInfo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoCuenta)
                            .addComponent(lblRut))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chkAhorro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkCorriente))
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(btnBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMostrarInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRut)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoCuenta)
                    .addComponent(chkAhorro)
                    .addComponent(chkCorriente))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String rut;
        char tipo = ' ';
        boolean ahorro, corriente;
        String tipox;
        int saldo;
        
        DefaultTableModel tabla = (DefaultTableModel) tblDatos.getModel();
        
        rut = txtRut.getText();
        ahorro = chkAhorro.isSelected();
        corriente = chkCorriente.isSelected();
        if(ahorro==true && corriente==false){
            tipo = 'A';
        }
        else if(ahorro==false && corriente==true){
            tipo = 'C';
        }
        
        System.out.println(tipo);
        //Limpiar
        tabla.setRowCount(0);
        
        //Buscar por rut y tipo
        if(rut.isEmpty()==false && (tipo=='A'||tipo=='C')){
            List<Cliente> listaRutTipo = RegistroCliente.getLista(rut, tipo);
        
            for (Cliente tmp : listaRutTipo) {
                rut = tmp.getRut();
                tipo = tmp.getCuenta().getTipoCuenta();
                if (tmp.getCuenta().getTipoCuenta() == 'A') {
                    tipox = "Ahorro";
                }
                else{
                    tipox = "Corriente";
                }
                saldo = tmp.getCuenta().getSaldo();
                tabla.addRow(new Object[]{rut, tipox, saldo});
            }
        }
        
        //Buscar solo por rut (ambos o ningun tipo seleccionados)
        else if(rut.isEmpty()==false && tipo == ' '){
            List<Cliente> listaRut = RegistroCliente.getLista(rut);
            
            for (Cliente tmp : listaRut) {
                rut = tmp.getRut();
                tipo = tmp.getCuenta().getTipoCuenta();
                if (tmp.getCuenta().getTipoCuenta() == 'A') {
                    tipox = "Ahorro";
                }
                else{
                    tipox = "Corriente";
                }
                saldo = tmp.getCuenta().getSaldo();
                tabla.addRow(new Object[]{rut, tipox, saldo});
            }
        }
        
        //Si el rut está vacio y ambos tipos
        else if(rut.isEmpty()&&tipo==' '){
            List<Cliente> listaTipo = RegistroCliente.getLista();
            for (Cliente tmp : listaTipo) {
                rut = tmp.getRut();
                tipo = tmp.getCuenta().getTipoCuenta();
                if (tmp.getCuenta().getTipoCuenta() == 'A') {
                    tipox = "Ahorro";
                }
                else{
                    tipox = "Corriente";
                }
                saldo = tmp.getCuenta().getSaldo();
                tabla.addRow(new Object[]{rut, tipox, saldo});
            }
        }
        //Si el rut vacio y hay un tipo marcado
        else{
            List<Cliente> listaTipo = RegistroCliente.getLista(tipo);
            for (Cliente tmp : listaTipo) {
                rut = tmp.getRut();
                tipo = tmp.getCuenta().getTipoCuenta();
                if (tmp.getCuenta().getTipoCuenta() == 'A') {
                    tipox = "Ahorro";
                }
                else{
                    tipox = "Corriente";
                }
                saldo = tmp.getCuenta().getSaldo();
                tabla.addRow(new Object[]{rut, tipox, saldo});
            }
        
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JCheckBox chkAhorro;
    private javax.swing.JCheckBox chkCorriente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMostrarInfo;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblTipoCuenta;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
